source 'https://rubygems.org'
ruby "1.9.3"

gem 'sinatra'
gem 'json'
gem 'sshkey'
gem 'rake'

group :test do
  gem 'codeclimate-test-reporter', require: nil
  gem 'rack-test'
  gem 'mocha', require: false
  gem 'webmock'
  gem 'pry'
end
